#define TTS_SOUND_EFFECT_RADIO "radio"
#define TTS_SOUND_EFFECT_ROBOT "robot"
#define TTS_SOUND_EFFECT_RADIO_ROBOT "radio_robot"
#define TTS_SOUND_EFFECT_MEGAPHONE "megaphone"
#define TTS_SOUND_EFFECT_MEGAPHONE_ROBOT "megaphone_robot"
