/mob/living/basic/flesh_spider/death(gibbed)
	. = ..()
	if(prob(50))
		new /obj/item/loot_mobs/fleshspider_tongue(get_turf(src))
	var/obj/effect/gibspawner/generic/gibs = new(get_turf(src))
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(qdel), gibs), 60 SECONDS)
	qdel(src)

/mob/living/basic/spider/giant/hunter/death(gibbed)
	. = ..()
	if(prob(60))
		new /obj/item/loot_mobs/hunterspider_claw(get_turf(src))
	var/obj/effect/gibspawner/generic/gibs = new(get_turf(src))
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(qdel), gibs), 60 SECONDS)
	qdel(src)

/mob/living/basic/faithless/death(gibbed)
	. = ..()
	if(prob(35))
		new /obj/item/loot_mobs/faithless_heart(get_turf(src))
	var/obj/effect/gibspawner/generic/gibs = new(get_turf(src))
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(qdel), gibs), 60 SECONDS)
	qdel(src)

/mob/living/basic/spider/sand/death(gibbed)
	. = ..()
	if(prob(60))
		new /obj/item/loot_mobs/hunterspider_claw(get_turf(src))
	var/obj/effect/gibspawner/generic/gibs = new(get_turf(src))
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(qdel), gibs), 60 SECONDS)
	qdel(src)

/mob/living/basic/hyperzombie/death(gibbed)
	. = ..()
	if(prob(50))
		new /obj/item/loot_mobs/hyperzombie_gland(get_turf(src))
	var/obj/effect/decal/cleanable/greenglow/radioactive/puddle = new(get_turf(src))
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(qdel), puddle), 60 SECONDS)
	qdel(src)

/mob/living/basic/killer/death(gibbed)
	. = ..()
	if(prob(50))
		new /obj/item/gun/ballistic/automatic/mini_uzi(get_turf(src))
		new /obj/item/suppressor(get_turf(src))
	if(prob(25))
		new /obj/item/grenade/frag(get_turf(src))
	var/obj/effect/gibspawner/generic/gibs = new(get_turf(src))
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(qdel), gibs), 60 SECONDS)
	qdel(src)
