/mob/living/basic/flesh_spider/death(gibbed)
	. = ..()
	if(prob(50))
		new /obj/item/loot_mobs/fleshspider_tongue(get_turf(src))
	new /obj/effect/gibspawner/generic(get_turf(src))
	qdel(src)

/mob/living/basic/spider/giant/hunter/death(gibbed)
	. = ..()
	if(prob(60))
		new /obj/item/loot_mobs/hunterspider_claw(get_turf(src))
	new /obj/effect/gibspawner/generic(get_turf(src))
	qdel(src)

/mob/living/basic/faithless/death(gibbed)
	. = ..()
	if(prob(35))
		new /obj/item/loot_mobs/faithless_heart(get_turf(src))
	new /obj/effect/gibspawner/generic(get_turf(src))
	qdel(src)
