/datum/asset/simple/lobby_fonts
	assets = list(
		"logo.png" = 'icons/ui/common/ss220.png',
		"lobby_background.png" = 'modular_bandastation/title_screen/icons/lobby_background.png',
		"lobby_ready.png" = 'modular_bandastation/title_screen/icons/lobby_ready.png',
		"lobby_join.png" = 'modular_bandastation/title_screen/icons/lobby_join.png',
		"lobby_character-setup.png" = 'modular_bandastation/title_screen/icons/lobby_character-setup.png',
		"lobby_collapse.png" = 'modular_bandastation/title_screen/icons/lobby_collapse.png',
		"lobby_observe.png" = 'modular_bandastation/title_screen/icons/lobby_observe.png',
		"lobby_button.png" = 'modular_bandastation/title_screen/icons/lobby_button.png',
		"lobby_changelog.png" = 'modular_bandastation/title_screen/icons/lobby_changelog.png',
		"lobby_disabled.png" = 'modular_bandastation/title_screen/icons/lobby_disabled.png',
		"lobby_highlight.png" = 'modular_bandastation/title_screen/icons/lobby_highlight.png',
		"lobby_manifest.png" = 'modular_bandastation/title_screen/icons/lobby_manifest.png',
		"lobby_poll.png" = 'modular_bandastation/title_screen/icons/lobby_poll.png',
		"lobby_settings.png" = 'modular_bandastation/title_screen/icons/lobby_settings.png',
		"lobby_picture.png" = 'modular_bandastation/title_screen/icons/lobby_picture.png',
		"lobby_notice.png" = 'modular_bandastation/title_screen/icons/lobby_notice.png',
		"lobby_shutter.png" = 'modular_bandastation/title_screen/icons/lobby_shutter.png',
	)
