/datum/emote_entry
	var/key
	var/name
	var/category

/datum/emote_entry/New(_key, _name, _category)
	. = ..()
	key = _key
	name = _name
	category = _category

GLOBAL_LIST_INIT(emote_registry, create_emote_registry())

/proc/create_emote_registry()
	var/list/L = list()
	L += new /datum/emote_entry("laugh", "Смеяться", "sound")
	L += new /datum/emote_entry("cry", "Плакать", "sound")
	L += new /datum/emote_entry("giggle", "Хихикать", "sound")
	L += new /datum/emote_entry("cough", "Кашлять", "sound")
	L += new /datum/emote_entry("scream", "Кричать", "sound")
	L += new /datum/emote_entry("choke", "Подавиться", "sound")
	L += new /datum/emote_entry("moan", "Стонать", "sound")
	L += new /datum/emote_entry("gasp", "Задыхаться", "sound")
	L += new /datum/emote_entry("sign", "Вздыхать", "sound")
	L += new /datum/emote_entry("sneeze", "Чихнуть", "sound")
	L += new /datum/emote_entry("sniff", "Шмыгнуть носом", "sound")
	L += new /datum/emote_entry("snore", "Храпеть", "sound")
	L += new /datum/emote_entry("whistle", "Свистеть", "sound")
	L += new /datum/emote_entry("yawn", "Зевать", "sound")
	L += new /datum/emote_entry("salute", "Салютовать", "sound")
	L += new /datum/emote_entry("snap", "Щёлкнуть пальцами", "sound")
	L += new /datum/emote_entry("crack", "Хрустеть пальцами", "sound")
	L += new /datum/emote_entry("clap", "Хлопать", "sound")


	L += new /datum/emote_entry("collapse", "Рухнуть", "action")
	L += new /datum/emote_entry("jump", "Прыгнуть", "action")
	L += new /datum/emote_entry("flip", "Кувырок", "action")
	L += new /datum/emote_entry("faint", "Потерять сознание", "action")
	L += new /datum/emote_entry("handshake", "Пожать руку", "action")
	L += new /datum/emote_entry("spin", "Покрутиться", "action")
	L += new /datum/emote_entry("spin", "Сделать кольцо из пальцев", "action")
	L += new /datum/emote_entry("glasses", "Приподнять очки", "action")
	L += new /datum/emote_entry("hand", "Приготовить руку", "action")
	L += new /datum/emote_entry("kiss", "Поцеловать", "action")
	L += new /datum/emote_entry("noogie", "Дать леща", "action")
	L += new /datum/emote_entry("shoesteal", "Украсть обувь", "action")
	L += new /datum/emote_entry("sway", "Качаться на месте", "action")
	L += new /datum/emote_entry("swear", "Ругнуться", "action")
	L += new /datum/emote_entry("taunt", "Дразнить", "action")
	L += new /datum/emote_entry("dance", "Танцевать", "action")
	L += new /datum/emote_entry("slap", "Дать пощёчину", "action")

	L += new /datum/emote_entry("smile", "Улыбнуться", "me")
	L += new /datum/emote_entry("shrug", "Пожать плечами", "me")
	L += new /datum/emote_entry("wave", "Помахать", "me")
	L += new /datum/emote_entry("scratch", "Почесаться", "me")
	L += new /datum/emote_entry("blush", "Краснеть", "me")
	L += new /datum/emote_entry("blink", "Моргать", "me")
	L += new /datum/emote_entry("blink_r", "Моргать быстро", "me")
	L += new /datum/emote_entry("bow", "Поклониться", "me")
	L += new /datum/emote_entry("chuckle", "Усмехнуться", "me")
	L += new /datum/emote_entry("clear", "Прочистить горло", "me")
	L += new /datum/emote_entry("cross", "Скрестить руки", "me")
	L += new /datum/emote_entry("dap", "Особое рукопожатие", "me")
	L += new /datum/emote_entry("tunesing", "Подпевать", "me")
	L += new /datum/emote_entry("sit", "Сесть", "me")
	L += new /datum/emote_entry("drool", "Пускать слюни", "me")
	L += new /datum/emote_entry("exhale", "Выдохнуть", "me")
	L += new /datum/emote_entry("gag", "Потужиться", "me")
	L += new /datum/emote_entry("grimace", "Скорчить рожицу", "me")
	L += new /datum/emote_entry("frown", "Смотреть в недоумении", "me")
	L += new /datum/emote_entry("glare", "Сверлить взглядом", "me")
	L += new /datum/emote_entry("grin", "Ухмыльнуться", "me")
	L += new /datum/emote_entry("shake", "Мотать головой", "me")
	L += new /datum/emote_entry("tilt", "Наклонить голову", "me")
	L += new /datum/emote_entry("smile", "Улыбнуться", "me")
	L += new /datum/emote_entry("smug", "Самодовольно улыбнуться", "me")
	L += new /datum/emote_entry("grumble", "Ворчать", "me")
	L += new /datum/emote_entry("shrug", "Пожать плечами", "me")
	L += new /datum/emote_entry("stare", "Пялиться", "me")
	L += new /datum/emote_entry("sulk", "Обидеться", "me")
	L += new /datum/emote_entry("tremble", "Дрожать в ужасе", "me")
	L += new /datum/emote_entry("twitch", "Сильно дёргаться", "me")
	L += new /datum/emote_entry("twitch_s", "Дёргаться", "me")
	L += new /datum/emote_entry("eyebrow", "Приподнять бровь", "me")
	L += new /datum/emote_entry("gurgle", "Побулькать", "me")
	L += new /datum/emote_entry("hug", "Обнимать", "me")
	L += new /datum/emote_entry("inhale", "Вдохнуть", "me")
	L += new /datum/emote_entry("airguitar", "Воображаемая гитара", "me")
	L += new /datum/emote_entry("burp", "Рыгнуть", "me")
	L += new /datum/emote_entry("mumble", "Бормотать", "me")
	L += new /datum/emote_entry("raise", "Поднять руку", "me")
	L += new /datum/emote_entry("pale", "Бледнеть", "me")
	L += new /datum/emote_entry("pout", "Надуть губы", "me")
	L += new /datum/emote_entry("flap", "Махать крыльями", "me")
	L += new /datum/emote_entry("aflap", "Махать крыльями агрессивно", "me")
	L += new /datum/emote_entry("scowl", "Хмуриться", "me")
	L += new /datum/emote_entry("wag", "Махать хвостом", "me")

	L += new /datum/emote_entry("ping", "Звенеть", "racial")
	L += new /datum/emote_entry("beep", "Бипнуть", "racial")
	L += new /datum/emote_entry("buzz", "Жужжать", "racial")
	L += new /datum/emote_entry("buzz2", "Жужжать раздражённо", "racial")
	L += new /datum/emote_entry("wave", "Махать", "racial")
	L += new /datum/emote_entry("whimper", "Хныкать", "racial")
	L += new /datum/emote_entry("look", "Посмотреть", "racial")
	L += new /datum/emote_entry("nod", "Кивнуть", "racial")
	L += new /datum/emote_entry("wink", "Подмигнуть", "racial")
	L += new /datum/emote_entry("shiver", "Дрожать", "racial")
	L += new /datum/emote_entry("laughevil", "Смеяться злорадно", "racial")

	L += new /datum/emote_entry("meow_t", "Мяукнуть", "tajaran")
	L += new /datum/emote_entry("mow", "Мяукнуть раздражённо", "tajaran")
	L += new /datum/emote_entry("purr_t", "Мурчать", "tajaran")
	L += new /datum/emote_entry("pur", "Мурчать кратко", "tajaran")
	L += new /datum/emote_entry("purrr", "Мурчать дольше", "tajaran")
	L += new /datum/emote_entry("hiss", "Шипеть", "tajaran")
	L += new /datum/emote_entry("hiss_t", "Шипеть", "tajaran")

	L += new /datum/emote_entry("howl", "Выть", "vulpkanin")
	L += new /datum/emote_entry("growl", "Рычать", "vulpkanin")
	L += new /datum/emote_entry("purr", "Урчать", "vulpkanin")
	L += new /datum/emote_entry("bark", "Гавкнуть", "vulpkanin")
	L += new /datum/emote_entry("wbark", "Дважды гавкнуть", "vulpkanin")

	L += new /datum/emote_entry("wing", "Расправить крылья", "moth")


	return L

/proc/get_emote_entry(key)
	for(var/datum/emote_entry/E in GLOB.emote_registry)
		if(E.key == key)
			return E
	return null

/proc/get_all_emotes()
	return GLOB.emote_registry.Copy()
