/datum/station_goal/bluespace_beacon
	name = "Маяк реальности"
	var/goal = 45000
	VAR_PRIVATE/cached_points

/obj/item/circuitboard/machine/bluespace_beacon
	name = "Маяк реальности"
	greyscale_colors = CIRCUIT_COLOR_COMMAND
	build_path = /obj/machinery/power/bluespace_beacon
	specific_parts = TRUE
	req_components = list(
		/datum/stock_part/capacitor/tier3 = 5,
		/datum/stock_part/servo/tier3 = 5,
		/obj/item/stack/cable_coil = 2,
	)

/datum/supply_pack/engineering/bluespace_beacon
	name = "Части маяка реальности"
	desc = "Ящик с платой маяка реальности"
	cost = CARGO_CRATE_VALUE * 24
	order_flags = ORDER_SPECIAL
	access_view = ACCESS_COMMAND
	contains = list(/obj/item/circuitboard/machine/bluespace_beacon)
	crate_name = "Ящик с частями маяка реальности"

/datum/station_goal/bluespace_beacon/get_report()
	return {"<b>Установка маяка реальности</b><br>
	Общими усилиями НаноТрейзен было разработано устройство Маяк Реальности.
	Оно удерживает нашу реальность от поглощения опасной аномалией Горизонт, что может поглотить всю Вселенную.<br>
	Данная станция находится в зоне досягаемости так называемой Зоны сдерживания Горизонта и входит в кольцо содержания, поэтому Центральным Командованием принято решение об установке на активе Маяка.
	Установка и запуск данного изобретения - крайне важная задача не только для НаноТрейзен, но и всех разумных существ.
	<br><br>
	Учтите, что устройство является экспериментальным и устанавливается из-за крайней необходимости. При его работе возможны неожиданные явления.
	<br>
	Департамент активов НаноТрейзен"}

/datum/station_goal/bluespace_beacon/on_report()
	var/datum/supply_pack/P = SSshuttle.supply_packs[/datum/supply_pack/engineering/bluespace_beacon]
	P.order_flags |= ORDER_SPECIAL_ENABLED

/datum/station_goal/bluespace_beacon/check_completion()
	if(..())
		return TRUE

	cached_points = 0
	for(var/obj/machinery/power/bluespace_beacon/beacon as anything in SSmachines.get_machines_by_type_and_subtypes(/obj/machinery/power/bluespace_beacon))
		cached_points = max(cached_points, beacon.current_charge)

	if(cached_points >= goal)
		return TRUE
	return FALSE

#define BEACON_POINTS_PER_W 4e-6
#define BEACON_BASE_POINTS 2
#define BEACON_NEAREST_MW(power) ((power) - (power) % (1 MEGA WATTS))
#define BEACON_RANDOM_SPAWN_CHANCE 5
#define BEACON_RANDOM_SPAWN_RADIUS 7
#define BEACON_PORTAL_EVENT_COOLDOWN (20 SECONDS)
#define BEACON_PORTAL_CHANCE_MIN 2
#define BEACON_PORTAL_CHANCE_MAX 35
#define BEACON_DEMONIC_INCURSION_CHANCE 1
#define BEACON_DEMONIC_INCURSION_PORTALS_MIN 1
#define BEACON_DEMONIC_INCURSION_PORTALS_MAX 2

/obj/machinery/power/bluespace_beacon
	name = "Маяк реальности"
	desc = "Стационарное устройство, предназначенное для локализации и подавления \
	экспансии аномальных зон с нарушенной онтологической консистентностью. Стабилизирует объективную действительность от \
	уничтожения последней опасной аномалией Горизонт."
	circuit = /obj/item/circuitboard/machine/bluespace_beacon
	icon = 'modular_bandastation/objects/icons/obj/machines/bluespace_tap.dmi'
	icon_state = "bluespace_tap"
	base_icon_state = "bluespace_tap"
	max_integrity = 300
	pixel_x = -32
	pixel_y = -32
	density = TRUE
	interaction_flags_machine = INTERACT_MACHINE_WIRES_IF_OPEN | INTERACT_MACHINE_ALLOW_SILICON | INTERACT_MACHINE_OPEN_SILICON | INTERACT_MACHINE_OFFLINE
	can_change_cable_layer = TRUE
	use_power = NO_POWER_USE
	luminosity = 1

	var/list/obj/structure/fillers = list()
	/// Current station-goal points generated by this beacon.
	var/current_charge = 0
	/// Points generated in the current process tick.
	var/mined_points = 0
	/// Current power draw from the cable network (W).
	var/actual_power_usage = 0
	/// Goal threshold, shown in UI.
	var/maximum_charge = 45000
	/// Prevents repeating completion announcements each tick.
	var/completion_announced = FALSE
	/// Completion announcement message.
	var/completion_announcement_text = "Устройство полностью заряжено и готово к работе. Переход на пассивное питание. \
	Модулирование беспричинного изменения реальности завершено. Инициализация поля подавления Горизонта."
	/// Locked base draw after full completion.
	var/post_completion_input_level = 2 MEGA WATTS
	/// Whether input controls are locked.
	var/input_locked = FALSE
	/// TRUE when we can draw some power now.
	var/inputting = FALSE
	/// Requested input draw from network (W).
	var/input_level = 50 KILO WATTS
	/// UI cap for input target.
	var/input_level_max = 30 MEGA WATTS
	/// Internal radio for engineering anomaly notifications.
	var/obj/item/radio/radio
	/// Encryption key used by the internal radio.
	var/radio_key = /obj/item/encryptionkey/headset_eng
	/// Engineering channel key.
	var/engineering_channel = RADIO_CHANNEL_ENGINEERING
	/// Next world.time when hostile portal event may trigger.
	var/next_portal_event_at = 0
	/// Weighted random outcomes that may appear around the beacon while charging.
	var/static/list/random_spawn_weights

/obj/machinery/power/bluespace_beacon/should_have_node()
	return TRUE

/obj/machinery/power/bluespace_beacon/Initialize(mapload)
	. = ..()
	if(!length(random_spawn_weights))
		random_spawn_weights = get_bluespace_beacon_random_spawn_weights()

	radio = new(src)
	radio.keyslot = new radio_key
	radio.set_on(TRUE)
	radio.set_broadcasting(TRUE)
	radio.set_listening(FALSE)
	radio.recalculateChannels()
	if(!islist(radio.channels) || !(engineering_channel in radio.channels))
		if(RADIO_CHANNEL_ENGINEERING in radio.channels)
			engineering_channel = RADIO_CHANNEL_ENGINEERING
		else if(length(radio.channels))
			engineering_channel = radio.channels[1]

	var/list/occupied = list()
	for(var/direct in list(EAST, WEST, SOUTHEAST, SOUTHWEST, NORTH, NORTHWEST, NORTHEAST))
		occupied += get_step(src, direct)

	for(var/turf/tile as anything in occupied)
		var/obj/structure/filler/filler = new(tile)
		filler.parent = src
		fillers += filler

	if(anchored)
		connect_to_network()
	START_PROCESSING(SSmachines, src)
	update_appearance()

/obj/machinery/power/bluespace_beacon/Destroy()
	STOP_PROCESSING(SSmachines, src)
	QDEL_NULL(radio)
	for(var/obj/structure/filler/filler as anything in fillers)
		qdel(filler)
	fillers.Cut()
	return ..()

/obj/machinery/power/bluespace_beacon/on_construction(mob/user)
	var/obj/structure/cable/cable = locate() in loc
	if(!QDELETED(cable))
		cable_layer = cable.cable_layer
		connect_to_network()

/obj/machinery/power/bluespace_beacon/screwdriver_act(mob/living/user, obj/item/tool)
	if(default_deconstruction_screwdriver(user, "bluespace_tap", "bluespace_tap", tool))
		update_appearance()
		return ITEM_INTERACT_SUCCESS
	return ITEM_INTERACT_BLOCKING

/obj/machinery/power/bluespace_beacon/crowbar_act(mob/living/user, obj/item/tool)
	if(default_deconstruction_crowbar(tool))
		return ITEM_INTERACT_SUCCESS
	return ITEM_INTERACT_BLOCKING

/obj/machinery/power/bluespace_beacon/multitool_act(mob/living/user, obj/item/tool)
	. = ..()
	if(. == ITEM_INTERACT_SUCCESS)
		connect_to_network()

/obj/machinery/power/bluespace_beacon/set_anchored(anchorvalue)
	. = ..()
	if(isnull(.))
		return
	if(anchored)
		connect_to_network()
	else
		disconnect_from_network()
	update_appearance()

/obj/machinery/power/bluespace_beacon/examine(mob/user)
	. = ..()
	if(powernet)
		. += span_notice("Подключен к электросети.")
	else
		. += span_warning("Не подключен к электросети.")

/obj/machinery/power/bluespace_beacon/update_icon_state()
	. = ..()
	if(actual_power_usage <= 0)
		icon_state = base_icon_state
	else
		icon_state = "[base_icon_state][get_icon_state_number()]"

/obj/machinery/power/bluespace_beacon/proc/get_icon_state_number()
	switch(actual_power_usage)
		if(0 to (50 KILO WATTS) - 1)
			return 0
		if((50 KILO WATTS) to (3 MEGA WATTS) - 1)
			return 1
		if((3 MEGA WATTS) to (8 MEGA WATTS) - 1)
			return 2
		if((8 MEGA WATTS) to (11 MEGA WATTS) - 1)
			return 3
		if((11 MEGA WATTS) to (15 MEGA WATTS) - 1)
			return 4
		else
			return 5

/obj/machinery/power/bluespace_beacon/update_overlays()
	. = ..()

	if(machine_stat & (BROKEN|NOPOWER))
		set_light(0)
	else if(actual_power_usage > 0)
		set_light(2, 1, "#6fa8ff")
	else
		set_light(1, 1, "#353535")

	if(actual_power_usage > 0)
		. += "screen"
		. += emissive_appearance(icon, "light_mask", src)

/obj/machinery/power/bluespace_beacon/power_change()
	. = ..()
	if(machine_stat & (BROKEN|NOPOWER))
		set_light(0)
	else
		set_light(1, 1, "#353535")
	if(.)
		update_icon()

/obj/machinery/power/bluespace_beacon/connect_to_network()
	if(powernet)
		disconnect_from_network()

	var/list/turfs_to_check = list(get_turf(src))
	for(var/direction in list(NORTH, SOUTH, EAST, WEST, NORTHEAST, NORTHWEST, SOUTHEAST, SOUTHWEST))
		var/turf/check_turf = get_step(src, direction)
		if(check_turf)
			turfs_to_check += check_turf

	for(var/turf/check_turf as anything in turfs_to_check)
		var/obj/structure/cable/cable_node = check_turf.get_cable_node(cable_layer)
		if(cable_node?.powernet)
			cable_node.powernet.add_machine(src)
			update_appearance()
			return TRUE


	update_appearance()
	return FALSE

/obj/machinery/power/bluespace_beacon/disconnect_from_network()
	. = ..()
	if(.)
		update_appearance()

/obj/machinery/power/bluespace_beacon/proc/get_available_power()
	// Keep high-draw behavior while respecting existing net accounting.
	return min(max(newavail(), surplus()), input_level)

/obj/machinery/power/bluespace_beacon/proc/announce_completion()
	if(completion_announced)
		return
	completion_announced = TRUE
	priority_announce(completion_announcement_text, sound = 'sound/effects/magic/lightning_chargeup.ogg', sender_override = "Система оповещений Маяка")

/obj/machinery/power/bluespace_beacon/proc/lock_to_base_consumption()
	if(input_locked)
		return
	input_locked = TRUE
	input_level = post_completion_input_level
	input_level_max = post_completion_input_level
	update_static_data_for_all_viewers()

/obj/machinery/power/bluespace_beacon/proc/radio_engineering_notice(message)
	if(!length(message))
		return
	if(length(radio?.channels) && !(engineering_channel in radio.channels))
		if(RADIO_CHANNEL_ENGINEERING in radio.channels)
			engineering_channel = RADIO_CHANNEL_ENGINEERING
		else if(length(radio.channels))
			engineering_channel = radio.channels[1]
	radio?.talk_into(src, message, engineering_channel)

/obj/machinery/power/bluespace_beacon/proc/get_portal_event_chance()
	if(input_level_max <= 0)
		return BEACON_PORTAL_CHANCE_MIN
	var/progress_ratio = clamp(input_level / input_level_max, 0, 1)
	return clamp(round(BEACON_PORTAL_CHANCE_MIN + (BEACON_PORTAL_CHANCE_MAX - BEACON_PORTAL_CHANCE_MIN) * progress_ratio), BEACON_PORTAL_CHANCE_MIN, BEACON_PORTAL_CHANCE_MAX)

/obj/machinery/power/bluespace_beacon/proc/get_portal_spawn_turf()
	var/turf/target_turf = get_safe_random_station_turf_equal_weight()
	if(!target_turf || target_turf.density || isspaceturf(target_turf))
		return null
	return target_turf

/obj/machinery/power/bluespace_beacon/proc/trigger_demonic_incursion()
	var/list/demon_spawners = get_bluespace_beacon_demonic_incursion_spawners()
	if(!length(demon_spawners))
		return FALSE

	var/created_portals = 0
	var/to_spawn = rand(BEACON_DEMONIC_INCURSION_PORTALS_MIN, BEACON_DEMONIC_INCURSION_PORTALS_MAX)
	for(var/i in 1 to to_spawn)
		var/turf/spawn_turf = get_portal_spawn_turf()
		if(!spawn_turf)
			continue
		var/spawn_type = pick_weight(demon_spawners)
		if(!spawn_type)
			continue
		new spawn_type(spawn_turf)
		created_portals++

	if(!created_portals)
		return FALSE

	radio_engineering_notice("Внимание: зафиксирован демонический прорыв! Обнаружено порталов: [created_portals].")
	return TRUE

/obj/machinery/power/bluespace_beacon/proc/trigger_hostile_portal_faction()
	var/list/factions = get_bluespace_beacon_portal_factions()
	if(!length(factions))
		return FALSE

	var/list/faction_weights = list()
	for(var/faction_name in factions)
		var/list/faction_data = factions[faction_name]
		if(!islist(faction_data))
			continue
		faction_weights[faction_name] = max(1, faction_data["weight"] || 1)

	var/faction_name = pick_weight(faction_weights)
	var/list/faction_data = factions[faction_name]
	if(!islist(faction_data))
		return FALSE

	var/turf/spawn_turf = get_portal_spawn_turf()
	if(!spawn_turf)
		return FALSE

	var/portal_name = faction_data["portal_name"]
	var/list/portal_mob_types = faction_data["mob_types"]
	var/portal_spawn_time = faction_data["spawn_time"]
	var/portal_max_mobs = faction_data["max_mobs"]
	var/list/portal_faction = faction_data["faction"]
	var/portal_lifetime = faction_data["lifetime"]

	new /obj/structure/spawner/bluespace_beacon_event(
		spawn_turf,
		portal_name,
		portal_mob_types,
		portal_spawn_time,
		portal_max_mobs,
		portal_faction,
		portal_lifetime,
	)

	radio_engineering_notice("Внимание: пространственный разрыв. Тип: [faction_name]. Локация: [get_area_name(spawn_turf)].")
	return TRUE

/obj/machinery/power/bluespace_beacon/proc/try_trigger_hostile_portal_event()
	if(input_locked || current_charge >= maximum_charge)
		return
	if(world.time < next_portal_event_at)
		return
	if(!prob(get_portal_event_chance()))
		return

	next_portal_event_at = world.time + BEACON_PORTAL_EVENT_COOLDOWN
	if(prob(BEACON_DEMONIC_INCURSION_CHANCE))
		if(trigger_demonic_incursion())
			return
	trigger_hostile_portal_faction()

/obj/machinery/power/bluespace_beacon/proc/get_random_spawn_turf()
	var/list/possible_turfs = list()
	for(var/turf/target_turf as anything in RANGE_TURFS(BEACON_RANDOM_SPAWN_RADIUS, src))
		if(target_turf == get_turf(src))
			continue
		if(target_turf.density || isspaceturf(target_turf))
			continue
		var/is_blocked = FALSE
		for(var/atom/movable/thing as anything in target_turf)
			if(thing.density)
				is_blocked = TRUE
				break
		if(is_blocked)
			continue
		possible_turfs += target_turf
	if(!length(possible_turfs))
		return null
	return pick(possible_turfs)

/obj/machinery/power/bluespace_beacon/proc/try_spawn_random_effect()
	if(input_locked || current_charge >= maximum_charge)
		return
	if(!prob(BEACON_RANDOM_SPAWN_CHANCE))
		return
	var/turf/spawn_turf = get_random_spawn_turf()
	if(!spawn_turf)
		return
	var/spawn_type = pick_weight(random_spawn_weights)
	if(!spawn_type)
		return
	var/atom/movable/spawned = new spawn_type(spawn_turf)
	var/spawned_name = spawned?.name || "неизвестный объект"
	if(length(radio?.channels) && !(engineering_channel in radio.channels))
		if(RADIO_CHANNEL_ENGINEERING in radio.channels)
			engineering_channel = RADIO_CHANNEL_ENGINEERING
		else
			engineering_channel = radio.channels[1]
	radio?.talk_into(src, "Внимание: зафиксирован локальный аномальный выброс. Объект: [spawned_name].", engineering_channel)

	try_trigger_hostile_portal_event()

/obj/machinery/power/bluespace_beacon/process(seconds_per_tick)
	if(machine_stat & (BROKEN|NOPOWER) || !anchored)
		if(actual_power_usage || inputting)
			actual_power_usage = 0
			inputting = FALSE
			update_appearance()
		return

	// Retry linking in case cables/layer were changed after placement.
	if(!powernet)
		connect_to_network()
		if(!powernet)
			if(actual_power_usage || inputting)
				actual_power_usage = 0
				inputting = FALSE
				update_appearance()
			return

	var/mining_power = get_available_power()
	if(mining_power > 1 MEGA WATTS)
		mining_power = BEACON_NEAREST_MW(mining_power)

	actual_power_usage = min(mining_power, input_level)
	inputting = actual_power_usage > 0
	add_load(actual_power_usage)

	if(actual_power_usage > 0)
		mined_points = min(BEACON_BASE_POINTS * (actual_power_usage / (50 KILO WATTS)), 20) + actual_power_usage * BEACON_POINTS_PER_W
		var/previous_charge = current_charge
		current_charge = min(maximum_charge, current_charge + mined_points)
		if(current_charge >= maximum_charge)
			lock_to_base_consumption()
			announce_completion()
		else if(current_charge > previous_charge)
			try_spawn_random_effect()
	else
		mined_points = 0

	update_appearance(UPDATE_ICON_STATE | UPDATE_OVERLAYS)

/obj/machinery/power/bluespace_beacon/ui_interact(mob/user, datum/tgui/ui)
	ui = SStgui.try_update_ui(user, src, ui)
	if(!ui)
		ui = new(user, src, "BluespaceBeacon", name)
		ui.open()

/obj/machinery/power/bluespace_beacon/ui_static_data(mob/user)
	. = list(
		"maximumCharge" = maximum_charge,
		"inputLevelMax" = input_level_max,
	)

/obj/machinery/power/bluespace_beacon/ui_data()
	var/charge_percent = (maximum_charge > 0) ? (current_charge / maximum_charge) * 100 : 0
	. = list(
		"inputting" = inputting,
		"inputAvailable" = get_available_power(),
		"charge" = charge_percent,
		"powerUsage" = actual_power_usage,
		"inputLevel" = input_level,
		"inputLocked" = input_locked,
	)

/obj/machinery/power/bluespace_beacon/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
	. = ..()
	if(.)
		return

	switch(action)
		if("input")
			if(input_locked)
				return TRUE
			var/target = params["target"]
			var/adjust = text2num(params["adjust"])
			if(target == "min")
				target = 0
				. = TRUE
			else if(target == "max")
				target = input_level_max
				. = TRUE
			else if(adjust)
				target = input_level + adjust
				. = TRUE
			else if(text2num(target) != null)
				target = text2num(target)
				. = TRUE
			if(.)
				target = round(target / (1 MEGA WATTS)) * (1 MEGA WATTS)
				input_level = clamp(target, 0, input_level_max)
				update_appearance()
				return TRUE

#undef BEACON_POINTS_PER_W
#undef BEACON_BASE_POINTS
#undef BEACON_NEAREST_MW
#undef BEACON_RANDOM_SPAWN_CHANCE
#undef BEACON_RANDOM_SPAWN_RADIUS
#undef BEACON_PORTAL_EVENT_COOLDOWN
#undef BEACON_PORTAL_CHANCE_MIN
#undef BEACON_PORTAL_CHANCE_MAX
#undef BEACON_DEMONIC_INCURSION_CHANCE
#undef BEACON_DEMONIC_INCURSION_PORTALS_MIN
#undef BEACON_DEMONIC_INCURSION_PORTALS_MAX
