# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# Metastation Cryo
# [templates.metastation_cryo]
# map_files = ["metastation_cryo.dmm"]
# directory = "_maps/bandastation/automapper/templates/metastation/"
# required_map = "MetaStation.dmm"
# coordinates = [133, 182, 1]
# trait_name = "Station"

# CentCom Crew Quarters
[templates.CentCom_kekypaj]
map_files = ["CentCom.dmm"]
directory = "_maps/bandastation/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [12, 53, 1]
trait_name = "CentCom"

# IceBoxStation Detective's Office
[templates.iceboxstation_detective_office]
map_files = ["iceboxstation_detective_office.dmm"]
directory = "_maps/bandastation/automapper/templates/iceboxstation/"
required_map = "IceBoxStation.dmm"
coordinates = [86, 161, 2]
trait_name = "Station"
