#!/bin/bash
set -e
# Generate maps
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/Birdshot/birdshot.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/Cyberiad/Cyberiad.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/Deltastation/DeltaStation2.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/IceBoxStation/IceBoxStation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/MetaStation/MetaStation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/NebulaStation/NebulaStation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/tramstation/tramstation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/wawastation/wawastation.dmm"
tools/nanomap_renderer/nanomap-renderer minimap --w 4080 --h 4080 "./_maps/map_files/Mining/Lavaland.dmm"
# Move and rename files so the game understands them
cd "data/minimaps"
mv "birdshot_nanomap_z1.png" "Birdshot Station_nanomap_z1.png"
mv "DeltaStation2_nanomap_z1.png" "Delta Station_nanomap_z1.png"
mv "IceBoxStation_nanomap_z1.png" "Ice Box Station_nanomap_z1.png"
mv "IceBoxStation_nanomap_z2.png" "Ice Box Station_nanomap_z2.png"
mv "IceBoxStation_nanomap_z3.png" "Ice Box Station_nanomap_z3.png"
mv "tramstation_nanomap_z1.png" "Tramstation_nanomap_z1.png"
mv "tramstation_nanomap_z2.png" "Tramstation_nanomap_z2.png"
mv "wawastation_nanomap_z1.png" "Wawastation_nanomap_z1.png"
mv "wawastation_nanomap_z2.png" "Wawastation_nanomap_z2.png"
cd "../../"
cp "data/minimaps/Birdshot Station_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Cyberiad_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Cyberiad_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Delta Station_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Ice Box Station_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Ice Box Station_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Ice Box Station_nanomap_z3.png" "icons/_nanomaps"
cp "data/minimaps/MetaStation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/NebulaStation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/NebulaStation_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Tramstation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Tramstation_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Wawastation_nanomap_z1.png" "icons/_nanomaps"
cp "data/minimaps/Wawastation_nanomap_z2.png" "icons/_nanomaps"
cp "data/minimaps/Lavaland_nanomap_z1.png" "icons/_nanomaps"
