directory = "_maps/map_files/Cyberiad/maintenance_modules/"

[rooms.arrivalscargolower]
modules = ["arrivalscargolower_1.dmm"]

[rooms.arrivalscargolower_attachment_a]
modules = ["arrivalscargolower_attachment_a_1.dmm"]

[rooms.arrivalscargosouthconnectorlower]
modules = ["arrivalscargosouthconnectorlower_1.dmm"]

[rooms.arrivalscargosouthconnectorlower_attachment_a]
modules = ["arrivalscargosouthconnectorlower_attachment_a_1.dmm"]

