#define JOB_NANOTRASEN_REPRESENTATIVE "Nanotrasen Representative"
#define JOB_BLUESHIELD "Blueshield"
#define JOB_MAGISTRATE "Magistrate"

#define JOB_DISPLAY_ORDER_NANOTRASEN_REPRESENTATIVE 2.5
#define JOB_DISPLAY_ORDER_MAGISTRATE 3.5
#define JOB_DISPLAY_ORDER_BLUESHIELD 35.5
