### Example:

#["Event Name"]
#
### The category of the event
# category = "Event Category"
#
# ### The description of the event
# description = "Event description..."
#
# ### The weight this event has in the random-selection process
# ### Higher weights are more likely to be picked
# ### 10 is the default weight. 20 is twice more likely; 5 is half as likely as thi.s default
# ### 0 here does NOT disable the event, it just makes it extremely unlikely
# weight = 10
#
# ### The earliest world.time that an event can start (round-duration in deciseconds)
# ### default: 12000 deciseconds (20 mintutes)
# earliest_start = 12000
#
# ### The minimum amount of alive, non-AFK human players on server required to start the event
# min_players = 0
#
# ### The maximum number of times this event can occur (naturally), it can still be forced
# ### By setting this to 0 you can effectively disable an event
# max_occurrences = 20
#
# ### String which should be in the SSgamemode.holidays list if you wish this event to be holiday-specific
# ### anything with a (non-null) holidayID which does not match holiday, cannot run
# ### Not sure if it's used by `Gamemode` subsystem
# holidayID = "HolydayId"
#
# ### Is this a wizard event?
# wizardevent = false
#
# ### Should we let the ghosts know this event is firing
# ### Should be disabled on events that fire a lot
# alert_observers = true
#
# ### Minimum wizard rituals at which to trigger this event, inclusive.
# ### -1 - never triggered
# ### 0-7 are valid ritual stages
# min_wizard_trigger_potency = -1
#
# ### Maximum wizard rituals at which to trigger this event, inclusive.
# ### -1 - never triggered
# ### 0-7 are valid ritual stages
# max_wizard_trigger_potency = -1
#
# ### Flags dictating whether this event should be run on certain kinds of map
# ### Possible values:
# ### - 0 - Event has no special requirements
# ### - 1 - Event can only run on a map set in space
# ### - 2 - Event can only run on a map which is a planet
# map_flags = 0
#
# ### Which track this event uses in storyteller system
# ### Possible values:
# ### - "Mundane"
# ### - "Moderate"
# ### - "Major"
# ### - "Roleset"
# track = "Moderate"
#
# ### Coefficient of event weight downscaling per occurance
# ### 1 - means weight won't downscale
# reoccurence_penalty_multiplier = 1
#
# ### List of tags that define event type. Empty by default - no tags.
# ### Possible values:
# ###	- "combat" - When the event is combat oriented (spawning monsters, inherently hostile antags)
# ###	- "spooky" - When the event is spooky (broken lights, some antags)
# ###	- "destructive" - When the event is destructive in a decent capacity (meteors, blob)
# ###	- "communal" - When the event impacts most of the crewmembers in some capacity (comms blackout)
# ###	- "targeted" - When the event targets a person for something (appendix, heart attack)
# ###	- "positive" - When the event is positive and helps the crew, in some capacity (Shuttle Loan, Supply Pod)
# ###	- "crew_antag" - When one of the crewmembers becomes an antagonist
# ###	- "team_antag" - When the antagonist event is focused around team cooperation.
# ###	- "away_antag" - When one of the non-crewmember players becomes an antagonist
# ###	- "overmap" - When the event impacts the overmap
# ###	- "space" - When the event requires the station to be in space (meteors, carp)
# ###	- "planetary" - When the event requires the station to be planetary.
# ###	- "external" - When the event is an external threat (meteors, nukies).
# ###	- "alien" - When the event is an alien threat (blob, xenos)
# ###	- "magical" - When the event is magical in nature
# tags = []
#
# ### List of departments to required crew amount. Key - department id, value - required crew amount (integer).
# ### Empty by default - no special department requirements
# ### Possible keys:
# ### - "head"
# ### - "med"
# ### - "eng"
# ### - "rnd"
# ### - "sec"
# req_departments_crew = []
#
# ### List of departments to required power. Key - department id, value - required power (integer).
# ### Empty by default - no special department requirements
# ### Possible keys:
# ### - "head"
# ### - "med"
# ### - "eng"
# ### - "rnd"
# ### - "sec"
# req_departments_power = []
