#!/usr/bin/env python3
"""
Assemble modular_bandastation translation_data/ru_names.toml from per-entry TOML files.

Expected layout:
  translation_data/ru_names/<stem>.toml

Older nested paths under ru_names (*.toml) are still merged for migration until removed.
Basic validation - invalid fragments and duplicate english keys are skipped (--strict exits non-zero).
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ru_names_common import build_fragment_body


REPO_TRANSLATION_DATA = Path("modular_bandastation/translations/code/translation_data")
DEFAULT_FRAGMENTS = REPO_TRANSLATION_DATA / "ru_names"
DEFAULT_OUTPUT = REPO_TRANSLATION_DATA / "ru_names.toml"

KNOWN_GENDER_VALUES = frozenset({"male", "female", "neuter", "plural"})
VALID_ASSIGNMENT_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass
class FragmentRecord:
    relative_path: Path
    english_key: str
    fields: dict[str, str]


def repo_root_from_script(script: Path) -> Path:
    return script.resolve().parent.parent.parent


def load_fragment_doc(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    return tomllib.loads(raw.decode("utf-8"))


def english_key_must_be_named_table(top: dict[str, Any]) -> tuple[str | None, str | None]:
    """
    Return (english_key, error_message). Expect exactly one TOML table at root mapping to a dict of str.
    """
    if not top:
        return None, "empty document"
    if len(top) != 1:
        return None, f"expected one root table, found {len(top)} keys: {sorted(top)!r}"
    (english_key, body), = top.items()
    if not isinstance(english_key, str) or not english_key.strip():
        return None, "root table key must be non-empty string"
    if not isinstance(body, dict):
        return None, "root table value must be a map of key/value pairs"
    return english_key.strip(), None


def map_fields_strict(body: dict[str, Any]) -> tuple[dict[str, str] | None, str | None]:
    flat: dict[str, str] = {}
    for k, v in body.items():
        if not isinstance(k, str):
            return None, f"illegal key type {type(k)!r}"
        if not VALID_ASSIGNMENT_KEY.fullmatch(k):
            return None, f"illegal assignment key `{k}` (must be bare TOML identifier)"
        if not isinstance(v, str):
            return None, f"`{k}` must be double-quoted string, got {type(v).__name__}"
        flat[k] = v
    return flat, None


def validate_semantics(fields: dict[str, str]) -> tuple[bool, str]:
    nominative = fields.get("nominative", "").strip()
    if not nominative:
        return False, 'missing or empty nominative'

    raw_gender = fields.get("gender")
    if raw_gender is None:
        return True, ""

    gv = raw_gender.strip().lower()
    if gv not in KNOWN_GENDER_VALUES:
        return False, f'unsupported gender `{raw_gender}` (allowed: {", ".join(sorted(KNOWN_GENDER_VALUES))})'
    return True, ""


def discover_fragments(root: Path) -> list[Path]:
    paths: list[Path] = []
    for path in sorted(root.rglob("*.toml")):
        if path.is_file():
            paths.append(path)
    return paths


def try_parse_record(path: Path, fragments_root: Path) -> tuple[FragmentRecord | None, list[str]]:
    try:
        path.relative_to(fragments_root)
    except ValueError:
        return None, [f"{path}: skip (not under {fragments_root})"]

    try:
        doc = load_fragment_doc(path)
    except Exception as exc:
        return None, [f"{path}: corrupt TOML ({exc})"]

    key_raw, structural_err = english_key_must_be_named_table(doc)
    if structural_err or key_raw is None:
        return None, [f"{path}: {structural_err}"]

    fields, ferr = map_fields_strict(doc[key_raw])
    if ferr:
        return None, [f"{path}: {ferr}"]

    assert fields is not None
    ok, sem_err = validate_semantics(fields)
    if not ok:
        return None, [f"{path}: {sem_err}"]

    return (
        FragmentRecord(
            relative_path=path.relative_to(fragments_root),
            english_key=key_raw,
            fields=fields,
        ),
        [],
    )


def sort_records(records: list[FragmentRecord]) -> list[FragmentRecord]:
    return sorted(
        records,
        key=lambda r: (r.english_key.lower(), str(r.relative_path).lower()),
    )


def compose_merged_toml(records: list[FragmentRecord]) -> str:
    lines: list[str] = [
        "# ru_names.toml generated by tools/ru_translations/merge_ru_names.py",
        "# Edit fragments under translation_data/ru_names/, then rebuild the game.",
        "",
    ]

    for rec in sort_records(records):
        body = build_fragment_body(rec.english_key, rec.fields)
        lines.append(body.rstrip("\n"))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def run_merge(
    fragments_root: Path,
    output_path: Path,
    *,
    strict: bool,
) -> int:
    if not fragments_root.is_dir():
        print(f"No fragments directory at {fragments_root}; skipping merge (existing {output_path} unchanged).")
        return 0

    discovered = discover_fragments(fragments_root)
    if not discovered:
        print(f"No *.toml under {fragments_root}; skipping merge (existing {output_path} unchanged).")
        return 0

    good: list[FragmentRecord] = []
    warns: list[str] = []

    for p in discovered:
        rec, errs = try_parse_record(p, fragments_root)
        if rec:
            good.append(rec)
        else:
            warns.extend(errs)

    duplicates = 0
    seen_keys: set[str] = set()
    unique: list[FragmentRecord] = []
    for entry in sort_records(good):
        if entry.english_key in seen_keys:
            warns.append(f"{fragments_root / entry.relative_path}: duplicate  english key `{entry.english_key}` (skipped)")
            duplicates += 1
            continue
        seen_keys.add(entry.english_key)
        unique.append(entry)

    for w in warns:
        print(w, file=sys.stderr)

    if not unique:
        print("ERROR: zero valid entries after validation; not writing output.", file=sys.stderr)
        if strict and warns:
            return 1
        return 2

    merged_text = compose_merged_toml(unique)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(merged_text, encoding="utf-8", newline="\n")

    print(
        f"Wrote {output_path} with {len(unique)} entries "
        f"({len(discovered)} files scanned; {len(warns)} issues reported; {duplicates} duplicates skipped).",
    )

    if strict and warns:
        return 1
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fragments-dir",
        type=Path,
        help=f"Folder with split ru_names (*.toml), default relative to repo: {DEFAULT_FRAGMENTS}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help=f"Destination ru_names.toml, default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any fragment is skipped (invalid TOML, bad keys, duplicates).",
    )
    ns = parser.parse_args(argv)

    repo = repo_root_from_script(Path(__file__))
    fragments = (repo / DEFAULT_FRAGMENTS) if ns.fragments_dir is None else ns.fragments_dir.expanduser().resolve()
    outfile = (repo / DEFAULT_OUTPUT) if ns.output is None else ns.output.expanduser().resolve()

    if ns.fragments_dir is not None and not fragments.is_absolute():
        fragments = (repo / fragments).resolve()

    if ns.output is not None and not outfile.is_absolute():
        outfile = (repo / outfile).resolve()

    return run_merge(fragments, outfile, strict=ns.strict)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
