# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# CENTRAL COMMAND MAP TEMPLATES
# CC Ferry Dock - Admin Shuttle
[templates.centcom_ferry_dock]
map_files = ["centcom_ferry_dock_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/centcom/"
required_map = "builtin"
coordinates = [128, 79, 1]
trait_name = "CentCom"

# CC Evac Docking Port Removal
[templates.centcom_shuttle_dock]
map_files = ["centcom_shuttle_dock_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/centcom/"
required_map = "builtin"
coordinates = [206, 85, 1]
trait_name = "CentCom"

# METASTATION MAP TEMPLATES
# Metastation Arrivals
[templates.metastaton_arrivals]
map_files = ["metastation_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [20, 107, 1]
trait_name = "Station"

# Metastation Cryo
[templates.metastation_cryo]
map_files = ["metastation_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [133, 182, 1]
trait_name = "Station"

# DELTASTATION MAP EDITS
# Deltastation Arrivals
[templates.deltastation_arrivals]
map_files = ["deltastation_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [126, 195, 1]
trait_name = "Station"

# Deltastation Cryo
[templates.deltastation_cryo]
map_files = ["deltastation_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [216, 93, 1]
trait_name = "Station"

# ICEBOX MAP EDITS
# Icebox Arrivals
[templates.icebox_arrivals]
map_files = ["icebox_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [8, 115, 3]
trait_name = "Station"

# Icebox Cryo
[templates.icebox_cryo]
map_files = ["icebox_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [117, 142, 3]
trait_name = "Station"

# TRAMSTATION MAP EDITS
# Tramstation Arrivals
[templates.tramstation_arrivals]
map_files = ["tramstation_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [8, 96, 2]
trait_name = "Station"

# Tramstation Cryo
[templates.tramstation_cryo]
map_files = ["tramstation_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [68, 102, 2]
trait_name = "Station"

# BIRDSHOT MAP EDITS
# Birdshot Arrivals
[templates.birdshot_arrivals]
map_files = ["birdshot_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [136, 61, 1]
trait_name = "Station"

# Birdshot Cryo
[templates.birdshot_cryo]
map_files = ["birdshot_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [136, 157, 1]
trait_name = "Station"

# NORTHSTAR MAP EDITS
# Northstar Cryo
[templates.northstar_cryo]
map_files = ["northstar_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/northstar/"
required_map = "north_star.dmm"
coordinates = [130, 114, 3]
trait_name = "Station"

# Northstar Arrivals
[templates.northstar_arrivals]
map_files = ["northstar_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/northstar/"
required_map = "north_star.dmm"
coordinates = [90, 100, 1]
trait_name = "Station"

# Lavaland NE Ashwalker Nest
[templates.lavaland_ashwalker_nenest]
map_files = ["lavaland_ashwalker_nenest_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/mining/"
required_map = "Lavaland.dmm"
coordinates = [223, 224, 1]
trait_name = "Mining"

# Kilostation Arrivals
[templates.kilostation_arrivals]
map_files = ["kilostation_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/kilostation/"
required_map = "KiloStation.dmm"
coordinates = [151, 80, 1]
trait_name = "Station"

# Kilostation Cryo
[templates.kilostation_cryo]
map_files = ["kilostation_cryo_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/kilostation/"
required_map = "KiloStation.dmm"
coordinates = [59, 118, 1]
trait_name = "Station"

# WAWASTATION MAP EDITS
# Wawastation Arrivals
[templates.wawastation_arrivals]
map_files = ["wawastation_arrivals_test.dmm"]
directory = "modular_bandastation/automapper/automapper_cfgs/templates/wawastation/"
required_map = "wawastation.dmm"
coordinates = [69, 81, 2]
trait_name = "Station"