name: Add new translation

on:
  workflow_dispatch:
  push:
    branches: ['translate']

concurrency:
  group: translation
  cancel-in-progress: false

jobs:
  add_translation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: 'Add new translation'

    steps:
      - name: 'Update Branch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run script
        run: ./tools/translate/add_new_translation.sh
