name: Update translation branch

on:
  workflow_dispatch:
  push:
    branches: ['master']

concurrency:
  group: translation
  cancel-in-progress: false

jobs:
  update_translation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: 'Update old translation'

    steps:
      - name: 'Update Branch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Git config'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "SS220Manager"

      - name: Merge with their incoming
        run: |
          git checkout origin/translate
          git merge origin/master --strategy-option theirs
          git push origin HEAD:translate

          
